version: '3.8'

services:
  postgres_db:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=sulthonuladib
      - POSTGRES_PASSWORD=Bedokkok11,.
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'


volumes:
  postgres
